esphome:
  name: test-esp32
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "test_wifi"
  password: "test_password"

# Enable logging
logger:

# Enable API
api:

# Enable Over-The-Air updates
ota:
  password: "test_ota_password"

# Enable web server
web_server:
  port: 80
